services:
  # api:
  #   build:
  #     context: ../
  #     dockerfile: Dockerfile.api
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - db

  db:
    container_name: docker-ums-db
    build:
      dockerfile: Dockerfile.db
    ports:
      - "5464:5432"